# Generated by Django 3.2.3 on 2021-06-14 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('idObra', models.IntegerField(primary_key=True, serialize=False, verbose_name='Id Obra')),
                ('nombreCategoria', models.CharField(max_length=20, verbose_name='Categoria Obras')),
            ],
        ),
        migrations.CreateModel(
            name='Obras',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre Obra')),
                ('autor', models.CharField(max_length=20, verbose_name='Autor')),
                ('tecnica', models.CharField(max_length=20, verbose_name='Tecnica')),
                ('precio', models.IntegerField(verbose_name='Precio')),
                ('dimension', models.CharField(blank=True, max_length=20, null=True, verbose_name='Dimension')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
    ]
