# Generated by Django 3.2.12 on 2022-07-04 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pedidos',
            fields=[
                ('idpedido', models.CharField(max_length=4, primary_key=True, serialize=False, verbose_name='Id Pedido')),
                ('nombreUsuario', models.CharField(max_length=20, verbose_name='Nombre Usuario')),
                ('combos', models.CharField(max_length=150, verbose_name='CombosPedidos')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('telefono', models.CharField(max_length=150, verbose_name='Telefono')),
                ('total', models.CharField(max_length=150, verbose_name='Total')),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre Combo')),
                ('porciones', models.CharField(max_length=20, verbose_name='Porciones')),
                ('imagen', models.CharField(max_length=150, verbose_name='Nombre archivo imagen')),
                ('descripcion', models.CharField(max_length=150, verbose_name='Descripcion')),
                ('precio', models.CharField(blank=True, max_length=20, null=True, verbose_name='Precio')),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('nombre', models.CharField(max_length=20, primary_key=True, serialize=False, verbose_name='Nombre')),
                ('contraseña', models.CharField(max_length=20, verbose_name='Contraseña')),
                ('correo', models.CharField(max_length=150, verbose_name='Correo')),
                ('telefono', models.CharField(max_length=20, verbose_name='Telefono')),
                ('direccion', models.CharField(max_length=150, verbose_name='Direccion')),
                ('tipo', models.CharField(max_length=50, verbose_name='Tipo usuario')),
            ],
        ),
    ]
